"""Train PairEncoder on precomputed BGE embeddings + scored_pairs.

Requires _emb.npz files alongside each event JSON (generated by
prepare_training_data.py after Task 4a changes).

Usage:
    python scripts/train_pair_encoder.py \\
        --data data/cphot/processed/train_all \\
        --output checkpoints/pair_enc_fold{fold}.pt
"""
from __future__ import annotations
import argparse
import json
import logging
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn
from sklearn.model_selection import KFold
from torch.utils.data import DataLoader, TensorDataset

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger(__name__)

import sys
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))
from mbridgenet.stage2.pair_encoder import PairEncoder, PLAT2IDX


def collect_features(data_dir: Path):
    """Load all labeled pairs with embeddings from a processed directory."""
    all_emb_a, all_emb_b, all_plat_a, all_plat_b, all_td, all_labels = [], [], [], [], [], []

    for json_path in sorted(data_dir.glob("*.json")):
        emb_path = json_path.with_name(json_path.stem + "_emb.npz")
        if not emb_path.exists():
            logger.warning("No embedding file for %s — skipping", json_path.stem)
            continue

        with open(json_path, encoding="utf-8") as f:
            ev = json.load(f)
        emb_data = np.load(emb_path)
        post_emb = {k: emb_data[k] for k in emb_data.files}

        post_meta = {}
        for p in ev.get("posts", []):
            ts = datetime.fromisoformat(p["timestamp"])
            if ts.tzinfo is None:
                ts = ts.replace(tzinfo=timezone.utc)
            post_meta[p["post_id"]] = {"platform": p["platform"], "timestamp": ts}

        for pair in ev.get("scored_pairs", []):
            if pair["label"] == -1:
                continue
            aid, bid = pair["post_a_id"], pair["post_b_id"]
            if aid not in post_emb or bid not in post_emb:
                continue
            if aid not in post_meta or bid not in post_meta:
                continue
            ma, mb = post_meta[aid], post_meta[bid]
            delta_h = abs((ma["timestamp"] - mb["timestamp"]).total_seconds() / 3600)
            all_emb_a.append(post_emb[aid])
            all_emb_b.append(post_emb[bid])
            all_plat_a.append(PLAT2IDX.get(ma["platform"], 0))
            all_plat_b.append(PLAT2IDX.get(mb["platform"], 0))
            all_td.append(delta_h)
            all_labels.append(float(pair["label"]))

    if not all_labels:
        raise ValueError("No labeled pairs with embeddings found in %s" % data_dir)

    return (
        torch.tensor(np.stack(all_emb_a), dtype=torch.float32),
        torch.tensor(np.stack(all_emb_b), dtype=torch.float32),
        torch.tensor(all_plat_a, dtype=torch.long),
        torch.tensor(all_plat_b, dtype=torch.long),
        torch.tensor(all_td, dtype=torch.float32),
        torch.tensor(all_labels, dtype=torch.float32),
    )


def train_fold(
    emb_a, emb_b, plat_a, plat_b, td, y,
    output_path: Path,
    epochs: int = 50,
    lr: float = 1e-3,
    weight_decay: float = 1e-3,
) -> float:
    model = PairEncoder()
    optimizer = torch.optim.Adam(model.parameters(), lr=lr, weight_decay=weight_decay)
    criterion = nn.BCELoss()
    dataset = TensorDataset(emb_a, emb_b, plat_a, plat_b, td, y)
    loader = DataLoader(dataset, batch_size=256, shuffle=True)

    for epoch in range(1, epochs + 1):
        model.train()
        total = 0.0
        for ea, eb, pa, pb, t, label in loader:
            optimizer.zero_grad()
            pred = model(ea, eb, pa, pb, t)
            loss = criterion(pred, label)
            loss.backward()
            optimizer.step()
            total += loss.item()
        if epoch % 10 == 0:
            logger.info("  epoch %d/%d  loss=%.4f", epoch, epochs, total / len(loader))

    output_path.parent.mkdir(parents=True, exist_ok=True)
    torch.save(model.state_dict(), output_path)
    logger.info("  saved → %s", output_path)
    return total / len(loader)


def main():
    parser = argparse.ArgumentParser(
        description="Train PairEncoder on BGE embeddings + scored_pairs"
    )
    parser.add_argument("--data",    required=True,
                        help="Directory containing *_emb.npz and *.json files")
    parser.add_argument("--output",  default="checkpoints/pair_enc_fold{fold}.pt")
    parser.add_argument("--epochs",       type=int, default=50)
    parser.add_argument("--lr",           type=float, default=1e-3)
    parser.add_argument("--weight-decay", type=float, default=1e-3, dest="weight_decay")
    parser.add_argument("--folds",        type=int, default=5)
    args = parser.parse_args()

    logger.info("Loading features from %s ...", args.data)
    emb_a, emb_b, plat_a, plat_b, td, y = collect_features(Path(args.data))
    logger.info("Dataset: %d labeled pairs  (pos=%d neg=%d)",
                len(y), int(y.sum()), int((y == 0).sum()))

    kf = KFold(n_splits=args.folds, shuffle=True, random_state=42)
    losses = []
    for fold, (train_idx, val_idx) in enumerate(kf.split(emb_a), start=1):
        logger.info("=== Fold %d/%d  (train=%d, val=%d) ===",
                    fold, args.folds, len(train_idx), len(val_idx))
        out = Path(args.output.replace("{fold}", str(fold)))
        loss = train_fold(
            emb_a[train_idx], emb_b[train_idx],
            plat_a[train_idx], plat_b[train_idx],
            td[train_idx], y[train_idx],
            out, args.epochs, args.lr, args.weight_decay,
        )
        losses.append(loss)
    logger.info("Mean final-epoch loss across folds: %.4f", float(np.mean(losses)))


if __name__ == "__main__":
    main()
